max_runs=8
sigma_e=0.01
sigma_i=0.01
a_min=2.
a_max=5.
a_max_min=3.
k_Hill=3.
t_orb=1.e7
N_pl=6
num_proc = 8
statuscode={"eject":2,"star":3,"collision":1,"survive":0}
basename='/home/cxhuang/mnt/scatt_Kepler/'
pythonpath='/home/cxhuang/src/virtualenv-1.5.2/ve/'
nnodes=20
